nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  "https://common.repositories.cloud.sap/artifactory/api/npm/deploy-releases-hyperspace-npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${BUILD_SECRETS_ARTIFACTORYTOKEN-}"

npmScopes:
  dxp:
    npmRegistryServer: "https://common.repositories.cloud.sap/artifactory/api/npm/deploy-releases-hyperspace-npm/"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
