nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  //europe-npm.pkg.dev/sap-gcp-dxp-prod/dxp/:
    npmAlwaysAuth: true
    npmAuthToken: "${GCP_REGISTRY_REFERENCE_TOKEN-}"

npmScopes:
  dxp:
    npmRegistryServer: "https://europe-npm.pkg.dev/sap-gcp-dxp-prod/dxp/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
