nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  https://common.repositories.cloud.sap/artifactory/api/npm/deploy-releases-hyperspace-npm/:
    npmAuthToken: "${REGISTRY_REFERENCE_TOKEN-}"
    npmAlwaysAuth: true

npmScopes:
  dxp:
    npmRegistryServer: https://common.repositories.cloud.sap/artifactory/api/npm/deploy-releases-hyperspace-npm/

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
