# Using Piper general purpose pipeline for Azure with pipeline optimization


schedules:
  - cron: '0 0 * * *' # cron: "*/5 * * * *"
    displayName: pipeline optimization
    always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.
    branches:
      include:
        - main

resources:
  repositories:
    - repository: piper-pipeline-azure
      endpoint: github.tools.sap
      type: githubenterprise
      name: project-piper/piper-pipeline-azure

extends:
  template: sap-piper-pipeline.yml@piper-pipeline-azure
  parameters:
    buildPreSteps:
      - task: piper@1
        name: AngularBuild
        displayName: Retrieve Google Artifact Registry Token
        inputs:
          stepName: shellExecute
