{{- if .Values.site.enable }}
apiVersion: extensions.dxp.sap.com/v1alpha1
kind: ExtensionClass
metadata:
  name: pipeline-ui
  namespace: root-universe
  labels:
    dxp.sap.com/hiddenExtension: "true"
spec:
  description: Enables hyperspace pipeline management.
  displayName: Pipelines
  supportsDynamicCdmUrls: false
  multipleInstallations: false
  {{- if .Values.documentation }}
  documentation:
    url: {{ .Values.documentation.url }}
  {{- end }}
  image: "{{ .Files.Get "assets/image.base64.txt" }}"
  cdm:
  - data: |-
{{- include "ui.cdm" . | indent 8 }}
  - url: {{ .Values.protocol }}://{{ .Values.site.wcDomain }}{{ .Values.site.wcCdmPath }}
  installableScopes:
    - Project
{{- if .Values.pilot }}
{{- range $idx, $namespace := .Values.pilot.namespaces }}
---
apiVersion: extensions.dxp.sap.com/v1alpha1
kind: ExtensionInstance
metadata:
  name: pipeline-ui
  namespace: {{ $namespace }}
spec:
  displayName: Pipelines
  extensionRef:
    name: pipeline-ui
    namespace: root-universe
  isMandatoryExtension: true
{{- end }}
{{- end }}
{{- end }}
