{{- if .Values.site.enable }}
apiVersion: extensions.dxp.sap.com/v1alpha1
kind: ExtensionClass
metadata:
  name: pipeline-ui
  namespace: root-universe
  labels:
    dxp.sap.com/hiddenExtension: "true"
spec:
  description: Enables hyperspace pipeline management.
  displayName: Pipelines
  supportsDynamicCdmUrls: false
  multipleInstallations: false
  {{- if .Values.documentation }}
  documentation:
    url: {{ .Values.documentation.url }}
  {{- end }}
  helpCenterData:
    issueTracker:
      url: https://itsm.services.sap/sp?id=sc_cat_item&sys_id=703f22d51b3b441020c8fddacd4bcbe2&service_offering=33e50476db98f110034ca8ebd39619bf&public=yes
    feedbackTracker:
      url: https://sapit-home-prod-004.launchpad.cfapps.eu10.hana.ondemand.com/site#feedbackservice-Display&/topic/cc5045ed-6c4e-4e7b-a18d-a0b377faf593/createFeedback
  image: "{{ .Files.Get "assets/image.base64.txt" }}"
  cdm:
  - data: |-
    {{- include "ui.cdm" . | indent 8 }}
  - data: |-
    {{- include "wc.cdm" . | indent 8 }}
  installableScopes:
    - Project
{{- if .Values.pilot }}
{{- range $idx, $namespace := .Values.pilot.namespaces }}
---
apiVersion: extensions.dxp.sap.com/v1alpha1
kind: ExtensionInstance
metadata:
  name: pipeline-ui
  namespace: {{ $namespace }}
spec:
  displayName: Pipelines
  extensionRef:
    name: pipeline-ui
    namespace: root-universe
  isMandatoryExtension: true
{{- end }}
{{- end }}
{{- end }}
