name: Build Packages Workflow
on: [push]

jobs:
  run:
    uses: dxp/.github/.github/workflows/job--ng-build.yaml@main
    secrets: inherit
    with:
      artifact: pipeline-frontend
      lint: false