name: Build Packages Workflow
on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/build-packages.yaml'
      - 'projects/ui/**'
      - 'package-lock.json'
      - 'package.json'

jobs:
  buildPackages:
    uses: dxp/.github/.github/workflows/job--ng-build.yaml@main
    secrets: inherit
    with:
      artifact: pipeline-frontend
      package_manager: "npm"
      hyperspace_project: "PIPELINE-GROUP-2044"
      build_command: 'npm run build:ui'
      test_command: 'npm run test:ui:cov'
      node-versions: '[ "20.x" ]'

  updateStackDev:
    needs: [buildPackages]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dxp/.github/.github/workflows/update-stack.yaml@main
    with:
      stackRepo: hyperspace/ci-cd-setup-stack
      stackRepoBranch: dev
      componentVersionKey: pipelineFrontend
      version: ${{ needs.buildPackages.outputs.version }}
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_HYPERSPACE_USER_TOKEN }}

  updateStackInt:
    needs: [buildPackages]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dxp/.github/.github/workflows/update-stack.yaml@main
    with:
      stackRepo: hyperspace/ci-cd-setup-stack
      stackRepoBranch: int
      componentVersionKey: pipelineFrontend
      version: ${{ needs.buildPackages.outputs.version }}
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_HYPERSPACE_USER_TOKEN }}
