name: Build WebComponent Workflow
on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/build-wc.yaml'
      - 'projects/webcomponent/**'
      - 'package-lock.json'
      - 'package.json'

jobs:
  buildPackages:
    uses: dxp/.github/.github/workflows/job--ng-build.yaml@main
    secrets: inherit
    with:
      artifact: pipeline-frontend-wc
      package_manager: 'npm'
      hyperspace_project: 'PIPELINE-GROUP-2044'
      build_command: 'npm run build:wc'
      test_command: 'npm run test:wc:cov'
      node-versions: '[ "20.x" ]'
      release_prefix: wc-

  updateStack:
    needs: [buildPackages]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: dxp/.github/.github/workflows/update-stack.yaml@main
    with:
      stackRepo: hyperspace/automaticd-stack
      stackRepoBranch: dev
      componentVersionKey: pipelineFrontendWebcomponent
      version: wc-${{ needs.buildPackages.outputs.version }}
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_HYPERSPACE_USER_TOKEN }}
