name: Piper
on:
  workflow_dispatch:
  pull_request:
  push: 
    branches:
    - main

jobs:
  piper:
    uses: project-piper/piper-pipeline-github/.github/workflows/sap-piper-workflow.yml@main
    secrets: inherit
